[project]
name = "ai-hpc-ansible"
version = "0.1.0"
description = "Ansible project for deploying and managing AI/HPC infrastructure"
readme = "README.md"
requires-python = ">=3.9"
authors = [
  { name = "Alistair Y. Lewars" },
]
