---
version: "3"

vars:
  VENV_NAME: .venv
  ENV: lab  # Default environment

tasks:
  info:
    desc: Show project information
    cmds:
      - |
          echo "Project: ai-hpc-ansible"
          echo "Version: 0.1.0"
          echo "Author: Alistair Y. Lewars"
          echo "Current Environment: {{.ENV}}"

  install_uv:
    desc: Install 'uv' if not present
    cmds:
      - command -v uv || pip install uv

  venv:
    desc: Create a Python 3.9.21 virtual environment
    cmds:
      - |
        echo "Creating virtual environment {{.VENV_NAME}}"
        uv venv {{.VENV_NAME}}

  activate:
    desc: Activate the virtual environment
    cmds:
      - echo "Activating virtual environment {{.VENV_NAME}}"
      - source {{.VENV_NAME}}/bin/activate

  lint:
    desc: Lint Ansible code
    cmds:
      - ansible-lint

  validate:
    desc: Validate Ansible playbooks
    cmds:
      - ansible-playbook --syntax-check playbook.yml

  test:
    desc: Run Molecule tests with Testinfra
    cmds:
      - cd roles/enroot && molecule test
      - cd roles/nvidia && molecule test
      - cd roles/pyxis && molecule test

  deploy:
    desc: Deploy to the specified environment (lab, dev, prod)
    cmds:
      - echo "Deploying to {{.ENV}} environment"
      - ansible-playbook -i inventory/{{.ENV}} playbook.yml

  deploy_lab:
    desc: Deploy to lab environment
    vars:
      ENV: lab
    cmds:
      - task: deploy

  deploy_dev:
    desc: Deploy to dev environment
    vars:
      ENV: dev
    cmds:
      - task: deploy

  deploy_prod:
    desc: Deploy to prod environment
    vars:
      ENV: prod
    cmds:
      - task: deploy

  clean:
    desc: Remove virtual environment and cleanup working directory
    cmds:
      - |
        echo "Cleaning up..."
        rm -rf {{.VENV_NAME}}
        find . -type d -name "__pycache__" -exec rm -r {} +
        find roles/ -type d -name ".ansible-tmp" -exec rm -r {} +
        rm -rf .pytest_cache/
        rm -f dist/*
