---
nvidia_package_manager: apt
nvidia_distribution: "{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}"
nvidia_driver_check_command: "dpkg -l | grep -q nvidia-driver"
nvidia_cuda_check_command: "dpkg -l | grep -q cuda-drivers"
