---
nvidia_package_manager: dnf
nvidia_distribution: "rhel{{ ansible_distribution_major_version }}"
nvidia_driver_check_command: "rpm -q nvidia-driver"
nvidia_cuda_check_command: "rpm -q cuda-drivers"
