---
- name: Check if local repo RPM exists
  ansible.builtin.stat:
    path: "{{ nvidia_local_repo_rpm }}"
  register: local_repo_rpm
  tags:
    - nvidia
    - nvidia_repo

- name: Install NVIDIA local repository RPM
  ansible.builtin.dnf:
    name: "{{ nvidia_local_repo_rpm }}"
    state: present
    disable_gpg_check: true
  when: local_repo_rpm.stat.exists and not nvidia_testing_mode
  tags:
    - nvidia
    - nvidia_repo

- name: Verify repository was installed
  ansible.builtin.stat:
    path: "/etc/yum.repos.d/nvidia-driver-local-rhel9-{{nvidia_driver_version}}.repo"
  register: repo_file
  tags:
    - nvidia
    - nvidia_repo

- name: Install NVIDIA driver and CUDA packages
  ansible.builtin.dnf:
    name:
      - nvidia-driver
      - nvidia-persistenced
      - cuda
    state: present
    disable_gpg_check: true
  when: repo_file.stat.exists and not nvidia_testing_mode
  tags:
    - nvidia
    - nvidia_driver

- name: Install NVIDIA Persistence Daemon
  ansible.builtin.dnf:
    name: nvidia-persistenced
    state: present
    disable_gpg_check: true
  when:
    - repo_file.stat.exists
    - nvidia_install_persistence_daemon | bool
    - not nvidia_testing_mode
  tags:
    - nvidia
    - nvidia_persistence

- name: Install NVIDIA Fabric Manager
  ansible.builtin.dnf:
    name: nvidia-fabricmanager
    state: present
    disable_gpg_check: true
  when:
    - repo_file.stat.exists
    - nvidia_install_fabricmanager | bool
    - not nvidia_testing_mode
  tags:
    - nvidia
    - nvidia_fabricmanager
