---
- name: Include default variables
  ansible.builtin.include_vars:
    file: "../defaults/main.yml"
  when: nvidia_cuda_initialize is not defined
  tags:
    - always

- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
    - "../vars/{{ ansible_os_family | lower }}.yml"
    - "../vars/default.yml"
  tags:
    - always

- name: Check if NVIDIA driver is already installed
  ansible.builtin.command: "{{ nvidia_driver_check_command }}"
  register: nvidia_driver_check
  ignore_errors: true
  changed_when: false
  check_mode: false
  tags:
    - nvidia
    - nvidia_driver

- name: Check if NVIDIA CUDA driver is already installed
  ansible.builtin.command: "{{ nvidia_cuda_check_command }}"
  register: nvidia_cuda_check
  ignore_errors: true
  changed_when: false
  check_mode: false
  tags:
    - nvidia
    - nvidia_cuda

- name: Install prerequisites for NVIDIA driver installation
  ansible.builtin.include_tasks: "prerequisites-{{ ansible_os_family | lower }}.yml"
  when: nvidia_driver_check.rc != 0
  vars:
    nouveau_blacklist: "{{ nouveau_blacklist }}"
  tags:
    - nvidia
    - nvidia_driver
    - nvidia_cuda
    - nvidia_nouveau

- name: Install NVIDIA driver from local repository
  ansible.builtin.include_tasks: "driver-{{ ansible_os_family | lower }}.yml"
  when:
    - nvidia_install_from_local_repo | bool
    - nvidia_driver_check.rc != 0
  tags:
    - nvidia
    - nvidia_driver
    - nvidia_cuda

- name: Configure CUDA environment
  ansible.builtin.include_tasks: "cuda.yml"
  when: nvidia_cuda_initialize | bool
  tags:
    - nvidia
    - nvidia_cuda

- name: Configure NVIDIA persistence daemon
  ansible.builtin.include_tasks: "persistence.yml"
  when: nvidia_install_persistence_daemon | bool
  tags:
    - nvidia
    - nvidia_persistence

- name: Configure NVIDIA Fabric Manager
  ansible.builtin.include_tasks: "fabricmanager.yml"
  when: nvidia_install_fabricmanager | bool
  tags:
    - nvidia
    - nvidia_fabricmanager

- name: Restart system if needed
  ansible.builtin.reboot:
    reboot_timeout: 600
    post_reboot_delay: 30
  when:
    - nvidia_driver_check.rc != 0
    - nvidia_restart_after_install | bool
    - not nvidia_testing_mode | bool
  tags:
    - nvidia
    - nvidia_reboot
