---
- name: Enable and start NVIDIA persistence daemon
  ansible.builtin.service:
    name: nvidia-persistenced
    state: started
    enabled: true
  when: not nvidia_testing_mode
  tags:
    - nvidia
    - nvidia_persistence
