---
- name: Install Enroot dependencies (RHEL/CentOS/Rocky)
  ansible.builtin.dnf:
    name: "{{ enroot_dependencies.redhat }}"
    state: present
  when: not enroot_testing_mode
  tags:
    - enroot
    - enroot_dependencies

- name: Download Enroot RPMs
  ansible.builtin.get_url:
    url: "{{ enroot_repo_url }}/v{{ enroot_version }}/{{ item }}-{{ enroot_version }}-1.x86_64.rpm"
    dest: "/tmp/{{ item }}-{{ enroot_version }}.rpm"
    mode: '0644'
  loop: "{{ enroot_packages }}"
  when: 
    - enroot_install_method == 'package'
    - not enroot_testing_mode
  tags:
    - enroot
    - enroot_download

- name: Install Enroot RPMs
  ansible.builtin.dnf:
    name: "/tmp/{{ item }}-{{ enroot_version }}.rpm"
    state: present
    disable_gpg_check: true
  loop: "{{ enroot_packages }}"
  when: 
    - enroot_install_method == 'package'
    - not enroot_testing_mode
  tags:
    - enroot
    - enroot_install

- name: Clean up temporary files
  ansible.builtin.file:
    path: "/tmp/{{ item }}-{{ enroot_version }}.rpm"
    state: absent
  loop: "{{ enroot_packages }}"
  when: enroot_install_method == 'package'
  tags:
    - enroot
    - enroot_cleanup

- name: Clone Enroot repository (source installation)
  ansible.builtin.git:
    repo: "https://github.com/NVIDIA/enroot.git"
    dest: "/tmp/enroot"
    version: "v{{ enroot_version }}"
  when: 
    - enroot_install_method == 'source'
    - not enroot_testing_mode
  tags:
    - enroot
    - enroot_source

- name: Build and install Enroot from source
  ansible.builtin.shell:
    cmd: |
      cd /tmp/enroot
      make
      make install
  when: 
    - enroot_install_method == 'source'
    - not enroot_testing_mode
  tags:
    - enroot
    - enroot_source

- name: Clean up source directory
  ansible.builtin.file:
    path: "/tmp/enroot"
    state: absent
  when: enroot_install_method == 'source'
  tags:
    - enroot
    - enroot_cleanup