---
driver:
  name: podman

platforms:
  - name: rhel9-instance
    image: rockylinux:9
    pre_build_image: true
    command: "sleep 1000000"
    volumes:
      - /opt/packages:/opt/packages

  - name: ubuntu2404-instance
    image: geerlingguy/docker-ubuntu2404-ansible
    pre_build_image: true
    command: "sleep 1000000"
    volumes:
      - /opt/packages:/opt/packages
    environment:
      DEBIAN_FRONTEND: noninteractive

provisioner:
  name: ansible
  env:
    ANSIBLE_PIPELINING: "True"
  inventory:
    group_vars:
      all:
        ansible_connection: podman
        nvidia_testing_mode: true
        nvidia_driver_check_command: "echo 'NVIDIA-SMI has failed'"

verifier:
  name: testinfra
  options:
    v: true
    s: true

scenario:
  name: default
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - verify
    - destroy
