---
- name: Prepare
  hosts: all
  gather_facts: true
  tasks:
    - name: Create mock directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - /etc/yum.repos.d
        - /etc/apt/preferences.d
        - /usr/share/keyrings
        - /etc/nvidia
        - /usr/bin
        - /usr/local/cuda/bin
        - /usr/local/cuda/lib64
      when: nvidia_testing_mode | default(true) | bool

    - name: Create mock NVIDIA GPG key
      copy:
        content: "mock GPG key for testing"
        dest: "/usr/share/keyrings/cuda-archive-keyring.gpg"
        mode: '0644'
      when:
        - nvidia_testing_mode | default(true) | bool
        - ansible_os_family == "Debian"

    - name: Create mock repository file for RHEL
      copy:
        content: |
          [cuda-rhel-x86_64]
          name=cuda-rhel-x86_64
          baseurl=file:///opt/rpms/
          enabled=1
          gpgcheck=0
        dest: "/etc/yum.repos.d/cuda-rhel.repo"
        mode: '0644'
      when:
        - nvidia_testing_mode | default(true) | bool
        - ansible_os_family == "RedHat"

    - name: Create mock pin file for Ubuntu
      copy:
        content: |
          Package: cuda*
          Pin: origin "developer.download.nvidia.com"
          Pin-Priority: 600
        dest: "/etc/apt/preferences.d/cuda-repository-pin-600"
        mode: '0644'
      when:
        - nvidia_testing_mode | default(true) | bool
        - ansible_os_family == "Debian"

    - name: Create mock nvidia-smi binary
      copy:
        content: |
          #!/bin/bash
          echo "NVIDIA-SMI 570.124.06    Driver Version: 570.124.06    CUDA Version: 12.3"
          echo "+-----------------------------------------------------------------------------+"
          echo "| NVIDIA-SMI 570.124.06    Driver Version: 570.124.06    CUDA Version: 12.3     |"
          echo "|-------------------------------+----------------------+----------------------+"
          echo "| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |"
          echo "| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |"
          echo "|                               |                      |               MIG M. |"
          echo "|===============================+======================+======================|"
          echo "|   0  NVIDIA A100-PCIE...  On | 00000000:01:00.0 Off |                    0 |"
          echo "| N/A   32C    P0    40W / 250W|      0MiB / 40960MiB |      0%      Default |"
          echo "|                               |                      |             Disabled |"
          echo "+-------------------------------+----------------------+----------------------+"
          exit 0
        dest: "/usr/bin/nvidia-smi"
        mode: '0755'
      when: nvidia_testing_mode | default(true) | bool

    - name: Create mock nvcc binary
      copy:
        content: |
          #!/bin/bash
          echo "nvcc: NVIDIA (R) Cuda compiler driver"
          echo "Copyright (c) 2005-2023 NVIDIA Corporation"
          echo "Built on Tue_Jun_13_15:08:56_PDT_2023"
          echo "Cuda compilation tools, release 12.3, V12.3.52"
          echo "Build cuda_12.3.r12.3/compiler.33281558_0"
          exit 0
        dest: "/usr/local/cuda/bin/nvcc"
        mode: '0755'
      when: nvidia_testing_mode | default(true) | bool

    - name: Create mock libcudart.so
      copy:
        content: "Mock CUDA Runtime"
        dest: "/usr/local/cuda/lib64/libcudart.so"
        mode: '0755'
      when: nvidia_testing_mode | default(true) | bool

    - name: Create mock CUDA environment file
      copy:
        content: |
          #!/bin/bash
          # CUDA environment variables
          export PATH=/usr/local/cuda-12.3/bin${PATH:+:${PATH}}
          export LD_LIBRARY_PATH=/usr/local/cuda-12.3/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
          export CUDA_HOME=/usr/local/cuda-12.3
        dest: "/etc/profile.d/cuda.sh"
        mode: '0644'
      when: nvidia_testing_mode | default(true) | bool

    - name: Create mock persistence daemon config
      copy:
        content: |
          # Configuration for NVIDIA Persistence Daemon
          # This file is managed by Ansible, any manual changes may be overwritten

          # Allow persistence daemon to run without root privileges
          nvidia-persistenced --no-persistenced-user --persistence-mode
        dest: "/etc/nvidia/nvidia-persistenced.conf"
        mode: '0644'
      when: nvidia_testing_mode | default(true) | bool

    - name: Mock systemd services for NVIDIA
      block:
        - name: Create systemd unit files directory
          file:
            path: /etc/systemd/system
            state: directory
            mode: '0755'

        - name: Create mock nvidia-persistenced service
          copy:
            content: |
              [Unit]
              Description=NVIDIA Persistence Daemon
              Wants=syslog.target

              [Service]
              Type=forking
              ExecStart=/usr/bin/nvidia-persistenced --verbose

              [Install]
              WantedBy=multi-user.target
            dest: "/etc/systemd/system/nvidia-persistenced.service"
            mode: '0644'

        - name: Create mock nvidia-fabricmanager service
          copy:
            content: |
              [Unit]
              Description=NVIDIA fabricmanager service
              Wants=syslog.target

              [Service]
              Type=simple
              ExecStart=/usr/bin/nvidia-fabricmanager

              [Install]
              WantedBy=multi-user.target
            dest: "/etc/systemd/system/nvidia-fabricmanager.service"
            mode: '0644'
      when: nvidia_testing_mode | default(true) | bool

    - name: Mock package installation for testing
      block:
        - name: Create mock NVIDIA package files for RPM-based systems
          file:
            path: "/usr/share/rpm/RPMS/{{ item }}"
            state: touch
            mode: '0644'
          with_items:
            - "nvidia-persistenced-570.124.06-1.x86_64.rpm"
            - "nvidia-fabricmanager-570.124.06-1.x86_64.rpm"
          when: ansible_os_family == "RedHat"

        - name: Create mock NVIDIA package status for Debian-based systems
          lineinfile:
            path: "/var/lib/dpkg/status"
            create: yes
            mode: '0644'
            line: |
              Package: {{ item }}
              Status: install ok installed
              Priority: optional
              Section: restricted/misc
              Installed-Size: 10000
              Version: 570.124.06-1
              Architecture: amd64

            insertafter: EOF
          with_items:
            - "nvidia-persistenced"
            - "nvidia-fabricmanager"
          when: ansible_os_family == "Debian"
      when: nvidia_testing_mode | default(true) | bool
