---
- name: Prepare
  hosts: all
  gather_facts: true
  tasks:
    - name: Install sudo on Rocky Linux
      package:
            name: sudo
            state: present
      when:
        - nvidia_testing_mode | default(true) | bool
        - ansible_os_family == "RedHat"

    - name: Install repository for Mainline kernel and upgrade
      ansible.builtin.shell:
        cmd: |
          add-apt-repository -y ppa:cappelikan/ppa &&
          apt update -y && apt upgrade -y
      when:
        - nvidia_testing_mode | default(true) | bool
        - ansible_os_family == "Debian"

